global:
  awsAccountId: "900182162489"
  awsRegion: "eu-west-1"
  ingress:
    host: "boutique.myser.serghini.me"
    certificateArn: "arn:aws:acm:eu-west-1:900182162489:certificate/cdffd0dd-0a5d-48b2-b686-f473ee69e5a3"
