global:
  awsAccountId: "900182162489"
  awsRegion: "eu-west-1"
  ingress:
    host: "boutique.myser.serghini.me"
    certificateArn: "arn:aws:acm:eu-west-1:900182162489:certificate/40a5c188-aa03-4988-8b16-08a5592ab76d"
