apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: 858093957996.dkr.ecr.eu-west-1.amazonaws.com/adservice:v1
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          readinessProbe:
            grpc:
              port: 9555
          livenessProbe:
            grpc:
              port: 9555
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - port: 9555
      targetPort: 9555
