apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: 858093957996.dkr.ecr.eu-west-1.amazonaws.com/cartservice:v1
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
          livenessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - port: 7070
      targetPort: 7070
