apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: 858093957996.dkr.ecr.eu-west-1.amazonaws.com/currencyservice:v1
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            grpc:
              port: 7000
          livenessProbe:
            grpc:
              port: 7000
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - port: 7000
      targetPort: 7000
