apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice
          image: 858093957996.dkr.ecr.eu-west-1.amazonaws.com/productcatalogservice:v1
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            grpc:
              port: 3550
          livenessProbe:
            grpc:
              port: 3550
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
    - port: 3550
      targetPort: 3550
      protocol: TCP