apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: 858093957996.dkr.ecr.eu-west-1.amazonaws.com/shippingservice:v1
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            grpc:
              port: 50051
          livenessProbe:
            grpc:
              port: 50051
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
    - port: 50051
      targetPort: 50051
