{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.global.awsAccountId }}.dkr.ecr.{{ $.Values.global.awsRegion }}.amazonaws.com/{{ .image }}:{{ .tag }}"
          ports:
            - containerPort: {{ .port }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          imagePullPolicy: IfNotPresent
          {{- if eq .probeType "grpc" }}
          readinessProbe:
            grpc:
              port: {{ .port }}
          livenessProbe:
            grpc:
              port: {{ .port }}
          {{- else if eq .probeType "http" }}
          readinessProbe:
            httpGet:
              path: {{ .probePath }}
              port: {{ .port }}
          livenessProbe:
            httpGet:
              path: {{ .probePath }}
              port: {{ .port }}
          {{- end }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
---
{{- end }}